[build]
  functions = "functions"
  publish = "public/"

[[redirects]]
  from = "/two/*"
  to = "https://repro2.netlify.app/.netlify/functions/:splat"
  status = 200
  force = true 

[[redirects]]
from = "/othersite"
to = "https://repro2.netlify.app/"
status = 200
force = true 

  