[build]
  functions = "functions"
  publish = "public/"

[[redirects]]
  from = "/two/*"
  to = "https://repro2.netlify.app/.netlify/functions/:splat"
  status = 200
  force = true 

[[redirects]]
from = "/myfunc"
to = "https://deploy-preview-1--repro2.netlify.app/myfunc"
status = 200
force = true 
headers = {X-From = "netlify"}

[[redirects]]
from = "/myotherfunc"
to = "https://deploy-preview-1--repro2.netlify.app/myotherfunc"
status = 200
force = true 
headers = {X-From = "netlify"}


  