[build]
  functions = "functions"
  publish = "public/"

  [[redirects]]
  from = "/two/myfunc"
  to = "https://repro2.netlify.app/.netlify/functions/myfunc"
  status = 200
  
[[redirects]]
  from = "/two/*"
  to = "https://repro2.netlify.app/:splat"
  status = 200

  